[project]
name = "c2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio[mcp]>=5.32.0",
    "huggingface-hub>=0.32.3",
    "rich>=14.0.0",
    "sambanova-gradio>=0.1.9",
]
