[project]
name = "c1"
version = "0.1.0"
description = "Various chat interface tests"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio[mcp]>=5.32.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "sseclient>=0.0.27",
]
